name: Paivita Liiga Koosteet

on:
  schedule:
    # Tämä ajaa koodin joka ilta klo 22:00 Suomen aikaa (klo 19:00 UTC)
    - cron: '0 19 * * *'
  workflow_dispatch: # Tämä sallii sinun käynnistää päivityksen myös käsin napista

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Varmistaa oikeuden tallentaa data.json takaisin
    steps:
    - name: Haetaan koodi
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Hakee koko historian, jotta push ei epäonnistu

    - name: Asennetaan Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Asennetaan tarvittavat kirjastot
      run: |
        pip install google-api-python-client huggingface_hub

    - name: Ajetaan Liiga-skripti
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        HF_API_KEY: ${{ secrets.HF_API_KEY }}
      run: python app.py

    - name: Tallennetaan uudet koosteet sivustolle automaattisesti
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automaattinen Liiga-päivitys (data.json)"
        file_pattern: 'data.json'
